### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by KiraLinux** [AlmuraDev/SGCraft#138]
add the gate from the stargate universe

I noticed that you added the gates of Atlantis and the sounds of these gates, but I would also like to add the gates from the stargate, the universe and the sounds of these gates

I think you saw this gate at work when you watched the series, well, of course, if you watched the series

![15011190675zvezdnye-vrata-vselennaya-stargate-universe-serial](https://user-images.githubusercontent.com/20641834/72466884-d6922b80-37ea-11ea-85d3-7708221c0a81.jpeg)

![1501119065315011190583zvezdnye-vrata-vselennaya-stargate-universe-serial](https://user-images.githubusercontent.com/20641834/72466907-e447b100-37ea-11ea-946e-93015d9193ef.jpeg)

**Comment by Dockter** [comment]
Easier said than done...

**Comment by uncoveredkhan09** [comment]
> Easier said than done...

Could you just create a new "skin" for the gate where the inner ring would cover the front face of the gate? Then just change the event horizon color to silver. I dont know much about coding so idk if that would be easy or not


The only part that could be tricky is making the chevrons light up on activation instead since theyd have to be part of the ring then the symbols light up instead while dialing.


But I'd be happy with it if it didnt light up at first because I know that would be much harder to code

**Comment by Dockter** [comment]
This is on my to-do list once I figure out in code to make what I need to do possible.
