### ISSUE TITLE
[feature Request] new dial plan

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/SGCraft#56]
so the 7 chevrons will stay the same but the 8th chevron will change between dim's
where the 8th will go between worlds

**Comment by Dockter** [comment]
What?  This literally makes zero sense.

**Comment by Ainsley4Ever** [comment]
I think he/she means that the address dialing mechanics when trying to join a gate in another dimension should be modified, so that they correspond more to that of the Stargate series. Normally, only 8 chevrons are needed to go to another galaxy (which would correspond to another dimension in Minecraft), and the ninth chevron is supposed to provide access to the Destiny, a vessel built by the Alterans. 
Personally, I find the idea interesting, since it would increase realism a little more in terms of address dialing. Of course I'm not saying it isn't realistic right now, and quite frankly I love the changes you made compared to the old SGCraft.

And just a suggestion: assuming this becomes true, maybe we should be able to use the ninth chevron to access a private gate network, thus overriding the function that blocks incoming wormholes (which you recently added), at the cost of a colossal amount of energy. This could add interesting strategy possibilities, especially on a pvp server, because it would prevent players from simply isolating themselves from the rest of the world.

**Comment by Dockter** [comment]
The problem with this scenario is that the addressing algorithm is built on a 9 digit string value for gates in various dimensions.  The 2 extra digits allow for the dimension dialing.  If its only a single digit then there would only be a possibility of 36 different dimensions.  If its two digits then it would be 1,296 different possibilities.

**Comment by Dockter** [comment]
Don't get me wrong, I like the idea of only a 8 chevron lock between different dimensions ID's, but mechanically isn't not possible without breaking the existing dialing algorithm.

**Comment by Ainsley4Ever** [comment]
Oh, I didn't see the problem that way. Maybe it would be possible to use the IDs of each dimension (including mods) to increase the number of possible combinations, but as you mentioned, this would require a complete change in the dialing mechanics... It's a bit of a shame, but it looks like we're going to have to stay with what we have.

**Comment by TherayTharow** [comment]
yeah; also world means how nukalis run worlds so 
how each world has it own end and nether and other dim's
world0-9th chevron 
|-The End from world0 only needs 8 chevrons but from world2 you need 9 
but was just a suggestion anyway
