### ISSUE TITLE
Incompatible with liteloader

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#96]
the game will crash immediately when i hit play if the version is forge that has liteloader installed on it, i need liteloader for my minimap of choice.

log: https://pastebin.com/TuinS49L

**Comment by shinji257** [comment]
The issue happens because LiteLoader bundles with Mixins 0.7.5 but SGCraft requires version 0.7.10 to function.  I've tried working around this myself and I've been unable to find a solution.  I believe the author of LiteLoader will have to update the Mixins version that is in use to resolve this issue.

**Comment by Dockter** [comment]
Give this a try:  http://solder.almuramc.com/downloads/liteloader-1.12.2-SNAPSHOT-release-1.jar

**Comment by shinji257** [comment]
That takes care of the Mixins issue.

**Comment by Dockter** [comment]
Do all the features of liteloader still appear to work?
